name: Java CI with Maven - Gsorrentino
on:
  push:
    branches: [ "master" ]
    paths:
      -  'src/**'
      - '.github/workflows/maven.yaml'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set up the Maven dependencies caching
      uses: actions/cache@v3.3.2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install Maven dependencies
      run: mvn install

    - name: Run tests
      run: mvn --batch-mode --update-snapshots verify
      
  docker-build:
  

      if: ${{ github.ref == 'refs/heads/master' }}
      runs-on: ubuntu-latest
      needs: [build]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 8
        - run: mvn -B package --file pom.xml -DskipTests
        - run: mkdir staging && cp target/*.war staging
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
             push: true
             context: .
             tags: ${{ secrets.DOCKERHUB_USERNAME }}/github_action02:latest
        - name: build image 
          run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github_action02:latest .
        - name: push image 
          run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/github_action02:latest
